### ISSUE TITLE
Allow to set custom GlobalAccelerator name

### ISSUE THREAD

**Issue by greatehop** [h3poteto/aws-global-accelerator-controller#164]
Hi

As feature request could you please add annotation to set custom GlobalAccelerator name.
Something like this:

`aws-global-accelerator-controller.h3poteto.dev/global-accelerator-name: <custom-ga-name>`

**Comment by h3poteto** [comment]
Why do you want it?

**Comment by greatehop** [comment]
In my case, we have naming convention for all AWS resources. 
It would be nice to set our own GA name instead of generated one.
