### ISSUE TITLE
should be able to run the controller in two regions (and have the controllers manage a single GAC)

### ISSUE THREAD

**Issue by thomas-b-jackson** [h3poteto/aws-global-accelerator-controller#183]
repro:
* run controller in two clusters: EKS us-west-2 and EKS us-east-1
* create an ingress in each region with aws-global-accelerator-controller.h3poteto.dev/global-accelerator-name=foo

expected:
* a single GAC is created (with name foo)
* GAC includes endpoints from east and west clusters

actual:
* two GACs are created (both named foo)
* each GAC includes endpoints from east or west clusters (but not both)

**Comment by h3poteto** [comment]
In this case, please use EndpointGroupBinding.

**Comment by thomas-b-jackson** [comment]
I am looking for a solution that doesn't involve using some outside agent (like terraform) to build the needed GAC infrastructure
