### ISSUE TITLE
Unable to delete EndpointGroupBinding if accelerator no longer exists

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [h3poteto/aws-global-accelerator-controller#198]
Error in the `aws-global-accelerator-controller-manager`:
```
E0715 21:51:05.433016       1 reconcile.go:49] operation error Global Accelerator: DescribeEndpointGroup, https response error StatusCode: 400, RequestID: 81e719b5-3ffa-45f4-99b8-0470bdde5f7d, EndpointGroupNotFoundException: EndpointGroup arn:aws:globalaccelerator::926093910549:accelerator/2d469309-bc50-4a16-8e6f-fe3576f794cf/listener/0393675a/endpoint-group/c67af2626002 does not exist.
```

**Comment by h3poteto** [comment]
How to reproduce this?

**Comment by gytis-ivaskevicius** [comment]
Given: I have ingress bound to accelerator using endpointBinding
When: I delete accelerator and then try to delete endpoint binding
Then: I am unable to delete endpoint binding

**Comment by h3poteto** [comment]
Ah, I got it.
Desired behavior is
- The controller cleans up AWS resources if the accelerator exists in AWS, then the binding resource is deleted.
- If the accelerator has already been deleted, we can delete the binding resource without cleaning up.
