### ISSUE TITLE
Why require cert-manager?

### ISSUE THREAD

**Issue by icco** [h3poteto/aws-global-accelerator-controller#207]
None of our other helmcharts that have webhooks require certmanager. Could you explain more in the readme why this is required or make it optional?

**Comment by h3poteto** [comment]
Because this controller uses a webhook server for validating. We need a certificate to deploy webhook servers, and cert-manager is easy to manage certificates.
If you don't need validation, you can skip cert-manager, but I don't recommend it.

**Comment by icco** [comment]
Right now this helmchart fails to install on clusters without cert-manger.

**Comment by h3poteto** [comment]
Yes, I don't recommend it.

**Comment by icco** [comment]
Would you be open to a PR to your helm chart to allow the webhook to run without certmanager? Is certmanager required by the code anywhere, or just so the webhook has a certificate on it?

**Comment by h3poteto** [comment]
>  Is certmanager required by the code anywhere

No, but it will no longer be validated. Is it okay?

**Comment by icco** [comment]
I created https://github.com/h3poteto/aws-global-accelerator-controller/pull/209 as a proposal for allowing running the webhook without SSL.

**Comment by h3poteto** [comment]
BTW, what happens if you disable webhook in helm chart?
https://github.com/h3poteto/charts/tree/master/stable/aws-global-accelerator-controller

Should I open a PR to use HTTP webhook?

**Comment by icco** [comment]
@h3poteto I took a pass at it with https://github.com/h3poteto/charts/pull/117. I haven't done much helm chart configuration before, so if there are things I should adjust please let me know. I'll be able to test it tomorrow when I'm back at work.
